La siguiente línea es para **importar la librería pandas**.

In [1]:
import pandas as pd

La siguiente línea es para **crear un diccionario con los datos de nombre, edad y género de tres personas**.

In [2]:
data = {"name": ["Sally", "Jhon", "Kim"], "age": [4, 6 ,7], "gender": ["female", "male", "male"]}

La siguiente línea es para **crear un DataFrame de pandas a partir del diccionario**.

In [3]:
pd.DataFrame(data)

    name  age  gender
0  Sally    4  female
1   Jhon    6    male
2    Kim    7    male

La siguiente línea es para **crear el mismo DataFrame, pero asignando un índice personalizado (Kid1, Kid2, Kid3)**.

In [4]:
pd.DataFrame(data, index = ["Kid1", "Kid2", "Kid3"])

       name  age  gender
Kid1  Sally    4  female
Kid2   Jhon    6    male
Kid3    Kim    7    male